################################################################################
# Shopping Web App - Simulates realistic e-commerce with configurable latency
# Replaces the basic sample web app for SRE Agent demo
################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-app-config
  namespace: default
data:
  # Latency simulation settings (in milliseconds)
  BASE_LATENCY_MS: "50"
  PRODUCT_LATENCY_MS: "200"
  CART_LATENCY_MS: "300"
  CHECKOUT_LATENCY_MS: "800"
  # Failure rates (0.0 to 1.0)
  DB_FAILURE_RATE: "0.05"
  PAYMENT_FAILURE_RATE: "0.10"
  # Enable chaos mode for higher latency/failures
  CHAOS_MODE: "false"
  CHAOS_LATENCY_MULTIPLIER: "10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
  namespace: default
  labels:
    app: shopping-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
        tier: frontend
    spec:
      containers:
      - name: shopping-app
        # TODO: Update with your container registry image
        # Build from src/Dockerfile: docker build -t <registry>/shopping-app:latest src/
        image: ${CONTAINER_REGISTRY}/shopping-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: shopping-app-config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-app-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: shopping-app
---
# Load generator for shopping app traffic simulation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-load-generator
  namespace: default
  labels:
    app: shopping-load-generator
    scenario: chaos-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-load-generator
  template:
    metadata:
      labels:
        app: shopping-load-generator
        scenario: chaos-demo
    spec:
      containers:
      - name: load-gen
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Starting shopping app load generator..."
          SHOP_URL="http://shopping-app-service"
          
          while true; do
            # Browse products
            curl -s "$SHOP_URL/api/products" > /dev/null
            curl -s "$SHOP_URL/api/products?category=electronics" > /dev/null
            curl -s "$SHOP_URL/api/products/1" > /dev/null
            curl -s "$SHOP_URL/api/products/5" > /dev/null
            
            # Cart operations
            USER_ID="user-$RANDOM"
            curl -s -X POST "$SHOP_URL/api/cart/$USER_ID/add" \
              -H "Content-Type: application/json" \
              -d '{"product_id": 1, "quantity": 1}' > /dev/null
            curl -s -X POST "$SHOP_URL/api/cart/$USER_ID/add" \
              -H "Content-Type: application/json" \
              -d '{"product_id": 3, "quantity": 2}' > /dev/null
            curl -s "$SHOP_URL/api/cart/$USER_ID" > /dev/null
            
            # Checkout (occasionally)
            if [ $((RANDOM % 3)) -eq 0 ]; then
              curl -s -X POST "$SHOP_URL/api/checkout" \
                -H "Content-Type: application/json" \
                -d "{\"user_id\": \"$USER_ID\"}" > /dev/null
            fi
            
            sleep 0.5
          done
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
